Update autojump

diff --git a/zsh/autojump b/zsh/autojump
--- a/zsh/autojump
+++ b/zsh/autojump
@@ -1,53 +1,118 @@
-#Copyright Joel Schaerer 2008, 2009
-#This file is part of autojump
+export AUTOJUMP_SOURCED=1
 
-#autojump is free software: you can redistribute it and/or modify
-#it under the terms of the GNU General Public License as published by
-#the Free Software Foundation, either version 3 of the License, or
-#(at your option) any later version.
-#
-#autojump is distributed in the hope that it will be useful,
-#but WITHOUT ANY WARRANTY; without even the implied warranty of
-#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#GNU General Public License for more details.
-#
-#You should have received a copy of the GNU General Public License
-#along with autojump.  If not, see <http://www.gnu.org/licenses/>.
+# set user installation paths
+if [[ -d ~/.autojump/bin ]]; then
+    path=(~/.autojump/bin ${path})
+fi
+if [[ -d ~/.autojump/functions ]]; then
+    fpath=(~/.autojump/functions ${fpath})
+fi
 
-#determine the data directory according to the XDG Base Directory Specification
-if [ -n "$XDG_DATA_HOME" ]
-then
-    export AUTOJUMP_DATA_DIR="$XDG_DATA_HOME/autojump"
+
+# set homebrew installation paths
+if command -v brew &>/dev/null && [[ -d "$(brew --prefix)/share/zsh/site-functions" ]]; then
+    fpath=("$(brew --prefix)/share/zsh/site-functions" ${fpath})
+fi
+
+
+# set error file location
+if [[ "$(uname)" == "Darwin" ]]; then
+    export AUTOJUMP_ERROR_PATH=~/Library/autojump/errors.log
+elif [[ -n "${XDG_DATA_HOME}" ]]; then
+    export AUTOJUMP_ERROR_PATH="${XDG_DATA_HOME}/autojump/errors.log"
 else
-    export AUTOJUMP_DATA_DIR=~/.local/share/autojump
+    export AUTOJUMP_ERROR_PATH=~/.local/share/autojump/errors.log
 fi
 
-if [ ! -e "${AUTOJUMP_DATA_DIR}" ]
-then
-    mkdir -p "${AUTOJUMP_DATA_DIR}"
-    mv ~/.autojump_py "${AUTOJUMP_DATA_DIR}/autojump_py" 2>>/dev/null #migration
-    mv ~/.autojump_py.bak "${AUTOJUMP_DATA_DIR}/autojump_py.bak" 2>>/dev/null
-    mv ~/.autojump_errors "${AUTOJUMP_DATA_DIR}/autojump_errors" 2>>/dev/null
+if [[ ! -d ${AUTOJUMP_ERROR_PATH:h} ]]; then
+    mkdir -p ${AUTOJUMP_ERROR_PATH:h}
 fi
 
-function autojump_preexec() {
-    {
-        (autojump -a "$(pwd -P)"&)>/dev/null 2>>|${AUTOJUMP_DATA_DIR}/.autojump_errors ;
-    } 2>/dev/null
-}
 
-typeset -ga preexec_functions
-preexec_functions+=autojump_preexec
-
-alias jumpstat="autojump --stat"
-
-function j {
-    local new_path="$(autojump $@)";
-    if [ -n "$new_path" ]; then
-        echo -e "\\033[31m${new_path}\\033[0m";
-        cd "$new_path";
+# change pwd hook
+autojump_chpwd() {
+    if [[ -f "${AUTOJUMP_ERROR_PATH}" ]]; then
+        autojump --add "$(pwd)" >/dev/null 2>>${AUTOJUMP_ERROR_PATH} &!
     else
-        false;
+        autojump --add "$(pwd)" >/dev/null &!
     fi
 }
-#  vim: set ts=4 sw=4 tw=79 ft=zsh fdm=syntax et :
+
+typeset -gaU chpwd_functions
+chpwd_functions+=autojump_chpwd
+
+
+# default autojump command
+j() {
+    if [[ ${1} == -* ]] && [[ ${1} != "--" ]]; then
+        autojump ${@}
+        return
+    fi
+
+    setopt localoptions noautonamedirs
+    local output="$(autojump ${@})"
+    if [[ -d "${output}" ]]; then
+        echo -e "\\033[31m${output}\\033[0m"
+        cd "${output}"
+    else
+        echo "autojump: directory '${@}' not found"
+        echo "\n${output}\n"
+        echo "Try \`autojump --help\` for more information."
+        false
+    fi
+}
+
+
+# jump to child directory (subdirectory of current path)
+jc() {
+    if [[ ${1} == -* ]] && [[ ${1} != "--" ]]; then
+        autojump ${@}
+        return
+    else
+        j $(pwd) ${@}
+    fi
+}
+
+
+# open autojump results in file browser
+jo() {
+    if [[ ${1} == -* ]] && [[ ${1} != "--" ]]; then
+        autojump ${@}
+        return
+    fi
+
+    setopt localoptions noautonamedirs
+    local output="$(autojump ${@})"
+    if [[ -d "${output}" ]]; then
+        case ${OSTYPE} in
+            linux*)
+                xdg-open "${output}"
+                ;;
+            darwin*)
+                open "${output}"
+                ;;
+            cygwin)
+                cygstart "" $(cygpath -w -a ${output})
+                ;;
+            *)
+                echo "Unknown operating system: ${OSTYPE}" 1>&2
+                ;;
+        esac
+    else
+        echo "autojump: directory '${@}' not found"
+        echo "\n${output}\n"
+        echo "Try \`autojump --help\` for more information."
+        false
+    fi
+}
+
+
+# open autojump results (child directory) in file browser
+jco() {
+    if [[ ${1} == -* ]] && [[ ${1} != "--" ]]; then
+        autojump ${@}
+        return
+    else
+        jo $(pwd) ${@}
+    fi
+}
